### ISSUE TITLE
Questions about MpGeneModel construction, how to merge annotation lists

### ISSUE THREAD

**Issue by hannahblau** [monarch-initiative/phenol#139]
@pnrobinson 
if gene of component MpSimpleModel does not match the gene of the MpGeneModel, should I log an error or throw a PhenolException? (could skip over the faulty model and maybe build the MpGeneModel from the other components if there are any good ones)

is it safe to assume that there are no ancestor/child pairs within the annotations of a single MpSimpleModel?

toss out any annotation that is negated (regardless of what is or is not already in the merged list of annotations)?

need an ontology object to tell me which termId is the descendant/ancestor of another; I assumed one would be provided as an argument to the constructor

if two annotations for same MPO term, one sex-specific and the other not, keep the sex-specific one but do I salvage any PMIDs or anything else from the annotation I am tossing?

if two annotations, both sex-specific, but one is male- and the other female- (could happen for the same MPO term if different genotypes involved) what to do?

if two annotations, one child sex-specific = no, other is ancestor but sex-specific = yes, toss the ancestor?

if all of the annotations for a particular MpSimpleModel are rejected, do I still add the genotype for that model to the list of components for the MpGeneModel under construction?

if two annotations for same MPO term are not in conflict then they should be merged? or one tossed and the other kept?

naive algorithm is O(n**2) (n == total number of annotations in all models to be merged) --- is it worth the effort to be more clever?

**Comment by pnrobinson** [comment]
if gene of component MpSimpleModel does not match the gene of the MpGeneModel, should I log an error or throw a PhenolException? (could skip over the faulty model and maybe build the MpGeneModel from the other components if there are any good ones)
=> Do not expose a method that would allow a user to try to merge MpSimpleModels that do not have the same gene

is it safe to assume that there are no ancestor/child pairs within the annotations of a single MpSimpleModel?
=> yes

toss out any annotation that is negated (regardless of what is or is not already in the merged list of annotations)?\
=> Yes, toss out

need an ontology object to tell me which termId is the descendant/ancestor of another; I assumed one would be provided as an argument to the constructor
=> The construction method should take a list of MpSimpleModels and a reference to the Ontology. It should return a list of MpGeneModels
```
List<MpGeneModel> createGeneModelList(List<MpSimpleModel, Ontology ontology) {
// create Map<TermId,Set<MpSimpleModel>
// with the TermId being a gene id
// for each TermId get Set<MpSimpleModel> and pass to the constructor for a single MpGeneModel
// Note that the MpGeneModel constructor is package-private and thus not in the public API of phenol
}

MpGeneModel(Set<MpSimpleModel, Ontology ontology) {
// in this case the set has all MpSimpleModels for a given gene 
}
```

if two annotations for same MPO term, one sex-specific and the other not, keep the sex-specific one but do I salvage any PMIDs or anything else from the annotation I am tossing?
=> Put all PMIDs into a set or list of the MpGeneModel

if two annotations, both sex-specific, but one is male- and the other female- (could happen for the same MPO term if different genotypes involved) what to do?
=> if we have both male and female sex specific, then "upgrade" the annotation to "sex-specific"

if two annotations, one child sex-specific = no, other is ancestor but sex-specific = yes, toss the ancestor?
=> always keep most specific term. For this use case, if any term is sex-specific, then everything is (transfer sex specific annotation to child if need be).

if all of the annotations for a particular MpSimpleModel are rejected, do I still add the genotype for that model to the list of components for the MpGeneModel under construction?
=> Yes

if two annotations for same MPO term are not in conflict then they should be merged? or one tossed and the other kept?
=> For now please log all candidate merges so that we can get a sense of the data

naive algorithm is O(n**2) (n == total number of annotations in all models to be merged) --- is it worth the effort to be more clever?
=> Start with naive algorithm, work from there.

**Comment by pnrobinson** [comment]
I am getting an error because we are trying to remove an annotation from an immutable set
```
Set<TermId> ancestors = mpo.getAncestorTermIds(child, false);
      // getAncestorTermIds method includes the starting vertex in the set of ancestors
      ancestors.remove(child);
```
lead to
```
Exception in thread "main" java.lang.UnsupportedOperationException
	at com.google.common.collect.ImmutableCollection.remove(ImmutableCollection.java:238)
```

**Comment by pnrobinson** [comment]
I am replacing these lines with this (from OntologyAlgorithm)
```
Set<TermId> ancestors=getAncestorTerms(mpo,child,false);
```
the arguments are mpo: the Ontology; child: the term; false: include original term in set of ancestors

**Comment by pnrobinson** [comment]
There is another issue
```
org.monarchinitiative.phenol.base.PhenolException: Attempt to merge annotations with distinct MP ids [MP:0005438/MP:0005439]
	at org.monarchinitiative.phenol.formats.mpo.MpAnnotation.merge(MpAnnotation.java:80)
	at org.monarchinitiative.phenol.formats.mpo.MpGeneModel.collapseSet(MpGeneModel.java:110)
	at org.monarchinitiative.phenol.formats.mpo.MpGeneModel.mergeAnnotations(MpGeneModel.java:93)
	at org.monarchinitiative.phenol.formats.mpo.MpGeneModel.mergeSimpleModels(MpGeneModel.java:57)
	at org.monarchinitiative.phenol.formats.mpo.MpGeneModel.mpgmConstructor(MpGeneModel.java:31)
	at org.monarchinitiative.phenol.formats.mpo.MpGeneModel.<init>(MpGeneModel.java:22)
	at org.monarchinitiative.phenol.io.obo.mpo.MpGeneParser.parseMpGeneModels(MpGeneParser.java:99)
	at org.monarchinitiative.dimorph.analysis.MpPhenoGeno.ingestMpData(MpPhenoGeno.java:77)
	at org.monarchinitiative.dimorph.analysis.MpPhenoGeno.<init>(MpPhenoGeno.java:57)
	at org.monarchinitiative.dimorph.command.Expression2PhenoCommand.execute(Expression2PhenoCommand.java:44)
	at org.monarchinitiative.dimorph.Dimorph.main(Dimorph.java:15)
```

**Comment by pnrobinson** [comment]
After long meditation and cal reflection it seems best to do the following
1. For exact matches (same MP term id), merge the annotations by set union (including annotations that may seem incompatbile such as both Male-specific and female specific)
2. For pairs of annotations in which one term is an ancestor of the other allow two options: (a) discard the ancestor term and do not transfer its metadata to the descendent (b) keep everything.

**Comment by pnrobinson** [comment]
continuing this work with #155 , closing here.
