### ISSUE TITLE
update owlapi dependency

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#164]
We now have 4.5.6 but maven central is up to 5.1. We may not benefit much from this, but we should update (which will mean some OWL-API API changes such that we need to refactor) to avoid getting stale. If there is some reason to stick with OWL-API 4.5, please somebody shout

**Comment by julesjacobsen** [comment]
OWLAPI essentially have two release versions - 4.x and 5.x The 5.x branch is java 8+ and they make heavy use of Stream so I think it's actually slower than the 4.x branch. Nonetheless we should stay with 4.5.6 because of the PR related to this on obographs:

https://github.com/geneontology/obographs/pull/40

**Comment by pnrobinson** [comment]
Let's leave things as they are for now then.
