### ISSUE TITLE
Add annotation sufficiency to phenol

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/phenol#236]
The current calculation of annotation sufficiency is not entirely meaningful from various perspectives.  I propose that we rework the calculation(s) and put them into phenol.

**Comment by pnrobinson** [comment]
I would suggest that we have a separate repository for the annotation sufficiency project and then make specific issues here for underlying algorithms. This issue is about 6-12 months of work and so is probably too much for a single issue. If you agree let's create a new repo at Monarch for the sufficiency project and close this issue?

**Comment by pnrobinson** [comment]
I will close this for now, let's regroup about this when we start the project!
