### ISSUE TITLE
TermAnnotation interface

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#356]
The Interface should not have Optionals in it. Instead, make another interface to extend TermAnnotation.
Also, it would be good to have a termplated interface (T for the annotated item, TermId for the GO or HP annotation)

Optional<Float> getFrequency()

**Comment by pnrobinson** [comment]
For use cases related to GO annotation, this interface needs to have getTermId() and getDomainItemId()
Occasionally we might want to perform HPO term overrepresentation analysis. But we should probably put the frequency etc into the implementation

Currently, getTermId() is not in the interface, but it needs to be.

**Comment by ielis** [comment]
Hi, the [`TermAnnotation`](https://github.com/monarch-initiative/phenol/blob/master/phenol-core/src/main/java/org/monarchinitiative/phenol/ontology/data/TermAnnotation.java) is currently pretty succinct. 

It provides:
- the ID of the annotation (e.g. HPO term ID)
- the ID of the world item (e.g. a disease, a subject)
- a `String` with the evidence code
- an optional frequency in percents.

I am not sure we need to generify the interface. Instead, I lean towards making the users of the interface generic. E.g. the code that performs the overrepresentation analysis can be generic over `TermAnnotation`, to be able to analyze any collection of world items - cohort of phenopackets, HPOA annotations, GO stuff..

There are few things we can change though. 
- consider moving the `TermAnnotation` and related classes into `phenol-analysis` module
- consider returning an `org.monarchinitiative.phenol.annotations.formats.EvidenceCode` enum from the `getEvidenceCode()` instead of the plain `String`
- consider returning `Ratio` instead of plain frequency `float`.

I see some potential for tweaking the data model here, but I don't want to overdo it unless it's really necessary. So, @pnrobinson pls comment if you think this needs attention. We can also address this later at some point.
