### ISSUE TITLE
 this.modesOfInheritance = Objects.requireNonNull(modesOfInheritance, "Modes of inheritance must not be null");

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#375]
In ``HpoDiseaseDefault`` we should allow an empty list because we may be annotating diseases that are not Mendelian or do not have this information. Possibly it would be better to demand this when we are parsing OMIM or DECIPHER or ORPHA

**Comment by ielis** [comment]
I think this is already possible; the `List<TermId> modesOfInheritance` can be empty, it just must not be `null` [here](https://github.com/monarch-initiative/phenol/blob/39d888961461e0ee7c2ac8dba669a8b07d5beba5/phenol-annotations/src/main/java/org/monarchinitiative/phenol/annotations/formats/hpo/HpoDiseaseDefault.java#L46). Or is there anything else I'm missing?

**Comment by pnrobinson** [comment]
Definitely. I think now that we can get a null pointer for this list, and the suggestion was to return an empty list instead

**Comment by ielis** [comment]
We can get a NPE upon creation of the object, which is the desired behavior. `null` values are not allowed. If you are getting NPE, then you're using the library in the wrong way, and you're being told at the place of mis-usage, instead of the undefined time in future. Therefore, the null check is there to stay.

It is a different question if we should make modes of inheritance mandatory for `HpoDisease`. If we want to be more specific, we should do:
```java
public interface InheritanceModeAware {
  List<TermId> modesOfInheritance();
}

public interface HpoDisease {
  // the previous definition without MOIs
}

public interface MendelianDisease extends HpoDisease, InheritanceModeAware {
   // ...
}
```
Right now, however, that seems like an overkill.

**Comment by julesjacobsen** [comment]
Depends on how lenient you want to be - if allowing `null` in the constructor, because really that's ok as you're going to just return an empty list anyway:

```java
this.onset = onset; // nullable
this.phenotypicAbnormalities = Objects.requireNonNull(phenotypicAbnormalities, "Phenotypic abnormalities must not be null");
this.modesOfInheritance = Objects.requireNonNullElse(modesOfInheritance, List.of());
```

Regarding `phenotypicAbnormalities` - shouldn't this actually require a non-empty list? If not, then it would make sense to use the same `requireNonNullElse` pattern. 

For `TemporalInterval` is it possible to define a null object such as `TemporalInterval.unknown()`?

Have you considered a builder if there are going to be several optional fields?

```java
var disease = HpoDiseaseDefault.builder()
                                 .diseaseId(diseaseId)
                                 .diseaseName(diseaseName)
                                 .phenotypicAbnormalities(phenotypicAbnormalities)
                                 .build();
```

or scoped static constructors, although these don't scale well...

```java
// actually required fields
var disease = HpoDiseaseDefault.of(diseaseId, diseaseName, phenotypicAbnormalities);
// required and optional fields
var diseaseWithOnset = HpoDiseaseDefault.of(diseaseId, diseaseName, phenotypicAbnormalities, onset);
var diseaseWithMois = HpoDiseaseDefault.of(diseaseId, diseaseName, phenotypicAbnormalities, modesOfInheritance);
var diseaseWithAllTheTrimmings = HpoDiseaseDefault.of(diseaseId, diseaseName, phenotypicAbnormalities, modesOfInheritance, onset);
```

**Comment by ielis** [comment]
My point of view on `null`s as input is: it is OK to provide `null` for nullable simple values but it is not OK to provide `null` for collections. I think an empty collection is proper there, unless it must be non-empty. For outputs, nullable values are wrapped in `Optional`, non-null values have regular getters.  Builders are indeed better for creating structures with plenty nullable values. I am not yet sure where to put a builder and where not in the code base.

I am not a fan of leniency in constructors. I think it is better to throw an error, as it is almost always received during development, and not in production use. Once the dust settles, I'll write docs to point out places where `null` is an error.


Thanks for pointing out non-empty list in `phenotypicAbormalities`, an empty list should indeed lead to an error.

Regarding `TemporalInterval.unknown()`, it is true that the code is a bit more verbose with `Optional<TemporalInterval>`, always having to keep in mind potential missing value. However, I am not sure the null object would help us. For instance, is it less or more than the other intervals? Do you think there are other reasons to add it?
