### ISSUE TITLE
AnnotationFrequency

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#431]
We probably want to keep this because we want to have the actual numerator and denominator (the frequency is not enough!)

@ielis @iimpulse

**Comment by ielis** [comment]
I am not sure I understand the big picture of the issue. NB, the latest phenol parses the HPOA data in 2 steps:
- `HpoaDiseaseDataLoader` just reads whatever is in the HPOA file, resulting in collections of objects with no preprocessing (`HpoaDiseaseDataContainer`). This is useful if one is interested in doing custom preprocessing or just presenting the HPOA data.
- `HpoDiseaseLoader` uses `HpoaDiseaseDataLoader` in the first step and *then* transforms the data into `HpoDiseases` (a container with disease objects)

So, if you want to access the primary data, use the `HpoaDiseaseDataLoader`. If you are OK with the transformation, use `HpoDiseases` etc.

**Comment by ielis** [comment]
@pnrobinson can you pls be more specific regarding what is the issue here?

I want to replace the `org.monarchinitiative.phenol.annotations.formats.hpo.AnnotationFrequency` interface by `Ratio` which is a like `AnnotationFrequency` but also provides the counts.

So, I'm closing the issue because I think the issue should be resolved, but pls comment if you think it should be re-opened.
