### ISSUE TITLE
csr limitation

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#444]
When trying to load maxo.json, I get this:
```
java.lang.RuntimeException: org.monarchinitiative.phenol.graph.csr.InsufficientWidthException: 
Unable to encode 159 relation types using 15 slots
```

I am guessing that for our purposes, we are only interested in is_a relations (in many cases) and that we could offer an option to ignore some relations? I haven't looked in the code, but what is the reason for limiting to 15 slots?

**Comment by ielis** [comment]
Looks weird, a possible bug, since the code should be using `Long` (64 slots) to encode the relationship types. So, 15 slots sounds like a bug.

On the other hand, if there indeed are 159 relation types in MAxO, we'll have to either just use `is_a` or rework the code. I thought 64 bits would be enough for our use cases..

**Comment by ielis** [comment]
FWIW,  MAxO v2023-10-03 can now be loaded by running this on the latest `develop`:

```java
  Path path = Path.of("path/to/maxo.json");
  CurieUtil curieUtil = CurieUtilBuilder.defaultCurieUtil();
  OntologyLoaderOptions options = OntologyLoaderOptions.builder()
    .discardNonPropagatingRelationships(true)
    .forceBuild(true)
    .build();
  MinimalOntology maxo = MinimalOntologyLoader.loadOntology(path.toFile(), curieUtil, options, "MAXO");
```

However, there is a disconnected node `MAXO:0001487`, so the build fails unless `.forceBuild(true)` is set.

Please reopen if you run into troubles again..
