### ISSUE TITLE
behavior of HPO Disease annotation parser

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#52]
Can we define the desired behavior of the HPO Disease annotation parser in phenol?

Options are
1. Completely fail if there is any error at all in the input file phenote.hpoa (this is probably the best, but we need to add in better warnings. Also, the warnings should be provided as exceptions that could be passed on to travis?
2. Skip malformed lines. I am going to implement this for not (TEMPORARILY) until all of the Q/C steps are sorted. I think this is just another few days, but I want to start to work on how phenol will interact with application code
3. ?

**Comment by yy20716** [comment]
It's just a preliminary opinion and I do not have much idea about the general size of this phenote.hpoa file. It is also possible that Chris would have different opinions about this issue, but I guess that the second option might be better than the first one even if your parser would be completed. If the file size is really big and the loading process is halted due to some minor errors, users might need to load the whole file again and again until they solve all errors, which could be a stressful process. They could see at least the preliminary results even though they skip a few lines with errors if we use the second option. Thank you.

**Comment by cmungall** [comment]
I'm cc-ing @dougl1sqrd who writes the equivalent python code for GAF parsing in the GO pipeline and is in charge of QC, also @kltm 

Our general strategy is fail-fast if there is a severe error. This blocks releases and requires someone to come and fix the issue. Examples of severe errors are malformed or truncated files, missing values that are syntactically required.

For other classes we warn and repair if possible. All warnings go in a report file that is read by the responsible curator for that particular GAF. This class includes:

 * if a class is obsolete, we flag it, and we repair if possible (replaced_by; but not 'consider')
 * if there are missing values that have no defaults, the annotation is reported and skipped

We have an identifier for each QC rule https://github.com/geneontology/go-site/tree/master/metadata/rules (kind of similar to python PEPs).

Of course, the GO situation is different from HPO. We are taking in GAFs from a variety of streams each with different timing cycles. If we threw an error any time anyone referenced an obsolete class the pipeline would never run. With HPO you have tighter control over the annotations, so you may want to fail fast sooner.

**Comment by pnrobinson** [comment]
For now, let's implement the parser to write error messages to STDERR. We can implement an optional "strict" version of the parser that would die if it encounters errors. The entire system should be set up so that the annotations are parseable without a single error.

**Comment by pnrobinson** [comment]
I have now implemented the parser to recover from errors with any given line, but to record each error in a list of strings. If client code wants to see it, then it can ask the parser if there were errors and can print out the errors to the shell or to a log.
