### ISSUE TITLE
 Set<TermId> ancTermIds = getAncestorTerms(ontology,abnMiddleEar);

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#72]
This kind of query is now returning the "All" term of the HPO, which is the actual root, but for many applications, we are interested in the ancestors up to and including "Phenotypic abnormality". I am not sure if it is a good idea to alter the API of these methods (addoing another parameters also adds to the complexity of the API). We now have this
```
public Set<TermId>   getAncestorTerms(Ontology<? extends Term, ? extends Relationship> ontology,
      Set<TermId> children,
      boolean includeOriginalTerm) {
//
}
```
and we could go to this
```
public Set<TermId>   getAncestorTerms(Ontology<? extends Term, ? extends Relationship> ontology,     TermId rootTerm,
      Set<TermId> children,
      boolean includeOriginalTerm) {
//
}
```
Ideas? Would this break anything in ontologies with many different roots (e.g., NCIT, I think?)

**Comment by cmungall** [comment]
Both of your code snippets are the same - did you mean this?

I think this is just the composition of an ancestor call with a set subtraction. E.g. `anc(Terms)-S`. I would not hardcode any particular value for `S` in core phenol. But I think having a static utility class that composes getAncestors and set subtraction in the core would be fine. This would also be useful for binning sets of terms into sub-root groupings.

Another way to approach it would be to operate on a subgraph of HPO, that is `HPO-"All"`.

Of course, no one would mourn the loss of "All" from HPO. It's only there because it used to be convention in obo format ontologies to always have a "root", even though this was never specified anywhere.

Side note: The notion of root is not straightforward in ontologies where you have imports. We should make sure phenol is robust to future use cases even if we are not worrying about it now. Operations to retrieve roots (and graph operations in general) should have a boolean to indicate whether `O` or `ImportClosure(O)` is used. Or the library should explicitly not support imports, and it should expect imports closures to be pre-merged. Either way it should be a conscious documented decision rather than ambiguous.

**Comment by pnrobinson** [comment]
The second snippet has an additional argument ``TermId rootTerm`` that specifies which term to use as the root. The previous implementation in ontolib had an object called HpoOntology that has a function called getPhenotypeSubontology. This was ok as far as it went, but in ontolib the function getTermMap still always returned all of the terms from the original ontology, and this caused a number of problems in my client code since I had not realized this. So essentially there are at least three choices for the architecture

1. Create separate wrapper classes for each ontology type that return subontologies that can be easily analyzed
2 Create versions of functions like "getAncestors" that can take specified root nodes
3 Let client code deal with  the fact that the actual root node may not always be the one you want if an ontology has subontologies like GO or HP.
4. Lose "all"
5. PS It seems that for client code, there is a utility in defining classes with "important" term Ids -- this would be a lot more robust that defining them as Strings in client code.

I have a feeling that there are some suboptimal design decisions that we might have made long ago that are leading to these difficulties...

**Comment by julesjacobsen** [comment]
Sounds like option 1.2 & 2 is the easiest for an external user to understand and also the simplest and most generalisable solution?

i.e. 
```java
public static Set<Term> getAncestorsOf(Term term, boolean includeTermInResult, Ontology ontology)
```
but should it not return a sub-graph and ```Ontology``` have a ```toSet()``` method?

**Comment by pnrobinson** [comment]
Another way to do things would be to let the user create subontologies from the complete ontology -- thus, the user could create a subontology for just Phenotypic abnormality and then the current implementation of getAncestors would work. @yy20716 Should we work now on porting the HPO ontology parsing code to the GenericTerm etc and then see if we can do this? After that, I would get rid of the HpoTerm and rename GenericTerm to simply Term ? After that, we could probably go maven central?

**Comment by yy20716** [comment]
* I am sorry for late response. If possible, I'd like to avoid the option 1 in Peter's suggestions. I wish to make a single, general function that returns (i) an OWLOntology instance corresponding to subontologies or (ii) a set of child terms based on the new (sub)root term. Then existing functions can be used without additional modifications. 

* One question I have is whether I can put this new function under the [OntologyAlgorithm](https://github.com/monarch-initiative/phenol/blob/develop/phenol-core/src/main/java/org/monarchinitiative/phenol/ontology/algo/OntologyAlgorithm.java), like all other general-purpose algorithms. If this is okay for you, I will begin working on this issue tomorrow.

* I will also see what I can do about Chris's side-note. Today I made a patch for getting the root term but it does not have options such as processing import statements or not, etc. I will work on this after finalizing this task. Thank you for your patience.

**Comment by pnrobinson** [comment]
1+

**Comment by pnrobinson** [comment]
I think this issue has gotten stale. We still do not have a function that does this but I would suggest reopen if the need arises again.
